// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuKsvAOuFP6J3Nr5YDey78-HsoIzOh9Bc',
    appId: '1:366660097336:web:eccf46eaa6b0dc8d841dcd',
    messagingSenderId: '366660097336',
    projectId: 'mqcart-prod',
    authDomain: 'mqcart-prod.firebaseapp.com',
    storageBucket: 'mqcart-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_N1NqQvs0kttuGx5aX9g_nhMzB0D56Y',
    appId: '1:366660097336:android:02fa473943e92a6d841dcd',
    messagingSenderId: '366660097336',
    projectId: 'mqcart-prod',
    storageBucket: 'mqcart-prod.firebasestorage.app',
  );

  // ⚠️ TODO(ios-setup): these values still point at the OLD Firebase iOS app
  // (bundle `com.example.mqcart`). After you register a new iOS app in the
  // `mqcart-prod` Firebase project with bundle id `com.mqcart.app.ios`, either
  // re-run `flutterfire configure` or paste the new `appId` / `iosClientId`
  // here and drop the matching `GoogleService-Info.plist` into `ios/Runner/`.
  // `apiKey` / `projectId` / `storageBucket` / `messagingSenderId` are
  // project-wide and do not change.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQoOm6j3aF3FyphU1E5O5iC4ay6V4l2Q',
    appId: '1:366660097336:ios:fc2be13748cbb028841dcd',
    messagingSenderId: '366660097336',
    projectId: 'mqcart-prod',
    storageBucket: 'mqcart-prod.firebasestorage.app',
    iosClientId: '366660097336-5fth38poc1ee5rhrntk9oira1226bhrp.apps.googleusercontent.com',
    iosBundleId: 'com.mqcart.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQoOm6j3aF3FyphU1E5O5iC4ay6V4l2Q',
    appId: '1:366660097336:ios:fc2be13748cbb028841dcd',
    messagingSenderId: '366660097336',
    projectId: 'mqcart-prod',
    storageBucket: 'mqcart-prod.firebasestorage.app',
    iosClientId: '366660097336-5fth38poc1ee5rhrntk9oira1226bhrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mqcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuKsvAOuFP6J3Nr5YDey78-HsoIzOh9Bc',
    appId: '1:366660097336:web:c280dcd783bf7829841dcd',
    messagingSenderId: '366660097336',
    projectId: 'mqcart-prod',
    authDomain: 'mqcart-prod.firebaseapp.com',
    storageBucket: 'mqcart-prod.firebasestorage.app',
  );
}
